import sys

HEADER = '''<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
'''

FOOTER = '</root>\n'

def xml_escape(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')

def gen(filename, translations):
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        for key, val in translations:
            f.write(f'  <data name="{key}" xml:space="preserve">\n')
            f.write(f'    <value>{xml_escape(val)}</value>\n')
            f.write(f'  </data>\n')
        f.write(FOOTER)

# Languages dict: code -> translator function
LANGS = ['en', 'fr-FR', 'zh-Hans', 'zh-Hant', 'ru-RU', 'de-DE', 'es-ES', 'it-IT', 'ko-KR', 'tr-TR', 'pt-PT', 'pl-PL', 'ja-JP', 'nl-NL', 'cs-CZ']

# Translation table: key -> dict of lang -> translation
# Format: key: {en: ..., fr-FR: ..., zh-Hans: ..., ...}
T = {
    'AppTitle': {'en': 'CopilotBuddy'},
    'SettingsTitle': {'en': 'Settings & Tools'},
    'PluginsTitle': {'en': 'Plugins'},
    'DeveloperToolsTitle': {'en': 'Developer Tools'},
    'SelectWoWTitle': {'en': 'Select a WoW'},
    'SelectWoWDescription': {'en': 'Select the WoW process to attach to:'},
    'LblAuthor': {'en': 'Author:'},
    'LblVersion': {'en': 'Version:'},
    'RecompileAll': {'en': 'Recompile All'},
    'LblFactionName': {'en': 'Faction Name:'},
    'LblGroupID': {'en': 'Group ID:'},
    'LblGroupID2': {'en': 'Group ID 2:'},
    'LblVendorType': {'en': 'Vendor Type:'},
    'LblRefresh': {'en': 'Refresh'},
    'LblLoadProfileButtonText': {'en': 'Load Profile'},
    'LblPauseButtonText': {'en': 'Pause'},
    'LblEnhancedMode': {'en': 'Enhanced Mode'},
    'LblFromFileSystem': {'en': 'From File System'},
    'LblFromBuddyStore': {'en': 'From Buddy Store'},
    'LblFromWebSource': {'en': 'From Web Source'},
    'LblRecent': {'en': 'Recent'},
    'LblShowPath': {'en': 'Show Path'},
    'LblTargetInfo': {'en': 'Target Info'},
    'LblNavigation': {'en': 'Navigation'},
    'ReportBug': {'en': 'Report a Bug'},
    'LblDungeonQueueType': {'en': 'You need to change Queue Type to Specific before editing the dungeon list'},
    'TabBagItems': {'en': 'Bag Items'},
    'LogNoneDesc': {'en': 'None: No logs'},
    'LogQuietDesc': {'en': 'Quiet: Minimal logs'},
    'LogNormalDesc': {'en': 'Normal: Standard logs'},
    'LogVerboseDesc': {'en': 'Verbose: Detailed logs'},
    'LogDiagnosticDesc': {'en': 'Diagnostic: All logs'},
    'GroupLanguage': {'en': 'Language'},
    'LblLanguage': {'en': 'Language:'},
    'LangAuto': {'en': 'Auto (system default)'},
    'LblLanguageRestart': {'en': 'Restart Honorbuddy for changes to take effect.'},
    'BGBuddyConfigTitle': {'en': 'BGBuddy Config'},
    'DungeonBuddyConfigTitle': {'en': 'DungeonBuddy Config'},
    'GatherBuddySettingsTitle': {'en': 'GatherBuddy Settings'},
    'TabLog': {'en': 'Log'},
    'TabInfo': {'en': 'Info'},
    'TabProfiles': {'en': 'Profiles'},
    'TabQuests': {'en': 'Quests'},
    'TabObjects': {'en': 'Objects'},
    'TabUnits': {'en': 'Units'},
    'Pause': {'en': 'Pause'},
    'Ready': {'en': 'Ready'},
    'EnhancedMode': {'en': 'Enhanced Mode'},
    'LoadProfile': {'en': 'Load Profile'},
    'Settings': {'en': 'Settings'},
    'BotConfig': {'en': 'Bot Config'},
    'ClassConfig': {'en': 'Class Config'},
    'Plugins': {'en': 'Plugins'},
    'DeveloperTools': {'en': 'Developer Tools'},
    'Start': {'en': 'Start'},
    'Stop': {'en': 'Stop'},
    'Navigation': {'en': 'Navigation'},
    'ShowPath': {'en': 'Show Path'},
    'TargetInfo': {'en': 'Target Info'},
    'ReloadScripts': {'en': 'Reload Scripts'},
    'DisableMovement': {'en': 'Disable Movement'},
    'EnableMovement': {'en': 'Enable Movement'},
    'CopyXML': {'en': 'Copy XML'},
    'Refresh': {'en': 'Refresh'},
    'SaveAndClose': {'en': 'Save & Close'},
    'Cancel': {'en': 'Cancel'},
    'Select': {'en': 'Select'},
    'SelectAll': {'en': 'Select All'},
    'UnselectAll': {'en': 'Unselect All'},
    'GenerateBlackspot': {'en': 'Generate Blackspot'},
    'GenerateHotspot': {'en': 'Generate Hotspot'},
    'GroupGeneral': {'en': 'General'},
    'GroupLogging': {'en': 'Logging'},
    'GroupMount': {'en': 'Mount'},
    'GroupVendorsFlightPaths': {'en': 'Vendors & Flight Paths'},
    'GroupMailRefreshments': {'en': 'Mail and Refreshments'},
    'GroupCombatLoot': {'en': 'Combat / Loot'},
    'GroupDeathSafety': {'en': 'Death / Safety'},
    'GroupGathering': {'en': 'Gathering'},
    'GroupAntiNinja': {'en': 'Anti-Ninja'},
    'GroupHerbs': {'en': 'Herbs'},
    'GroupMinerals': {'en': 'Minerals'},
    'GroupBagItems': {'en': 'Bag Items'},
    'GroupBossList': {'en': 'Boss List'},
    'GroupCommon': {'en': 'Common'},
    'GroupCopyInfo': {'en': 'Copy Info'},
    'GroupCopyXML': {'en': 'Copy XML'},
    'GroupCurrentTargetInfo': {'en': 'Current Target Info'},
    'GroupDistance': {'en': 'Distance'},
    'GroupDungeonList': {'en': 'Dungeon List'},
    'GroupDungeonSelection': {'en': 'Dungeon Selection'},
    'GroupEntry': {'en': 'Entry'},
    'GroupFactionID': {'en': 'Faction ID'},
    'GroupGUID': {'en': 'GUID'},
    'GroupGameObjects': {'en': 'Game Objects'},
    'GroupLocalPlayerInfo': {'en': 'Local Player Info'},
    'GroupLockType': {'en': 'LockType'},
    'GroupLootList': {'en': 'Loot List'},
    'GroupLooting': {'en': 'Looting'},
    'GroupMail': {'en': 'Mail'},
    'GroupName': {'en': 'Name'},
    'GroupNavigation': {'en': 'Navigation'},
    'GroupNodeSelection': {'en': 'Node Selection'},
    'GroupPosition': {'en': 'Position'},
    'GroupQueue': {'en': 'Queue'},
    'GroupSecret': {'en': 'Secret'},
    'GroupSellQualityFilters': {'en': 'Sell Quality Filters'},
    'GroupSessionTimer': {'en': 'Session Timer'},
    'GroupSettings': {'en': 'Settings'},
    'GroupSpellFocus': {'en': 'SpellFocus'},
    'GroupStackCount': {'en': 'StackCount'},
    'GroupTargetList': {'en': 'Target List'},
    'GroupType': {'en': 'Type'},
    'GroupVendorRepair': {'en': 'Vendor / Repair'},
    'GroupViewAuras': {'en': 'View Auras'},
    'ChkUseMount': {'en': 'Use Mount'},
    'ChkRandomMount': {'en': 'Random Mount'},
    'ChkAutomatic': {'en': 'Automatic'},
    'ChkLearnFlightPaths': {'en': 'Learn Flight Paths'},
    'ChkUseFlightPaths': {'en': 'Use Flight Paths'},
    'ChkFindVendorsAuto': {'en': 'Find Vendors Automatically'},
    'ChkTrainNewSkills': {'en': 'Train New Skills'},
    'ChkLogoutForInactivity': {'en': 'Logout For Inactivity'},
    'ChkUseFrameLock': {'en': 'Use Frame Lock'},
    'ChkKillBetweenHotspots': {'en': 'Kill Between Hotspots'},
    'ChkHearthExitTimer': {'en': 'Hearthstone & Exit on Timer'},
    'ChkWaitRezSickness': {'en': 'Wait Out Rez Sickness'},
    'ChkUseSpiritHealer': {'en': 'Use Spirit Healer (skip corpse run)'},
    'ChkVendorWhenFull': {'en': 'Go To Vendor When Bags Full'},
    'ChkRepairAtVendor': {'en': 'Repair At Vendor'},
    'ChkSkinMobs': {'en': 'Skin Mobs'},
    'ChkNinjaSkin': {'en': 'Ninja Skin'},
    'ChkLootMobs': {'en': 'Loot Mobs'},
    'ChkLootChests': {'en': 'Loot Chests'},
    'ChkLootCorpses': {'en': 'Loot Corpses'},
    'ChkMailToAlt': {'en': 'Mail Items To Alt'},
    'ChkNoNinja': {'en': "Don't Steal Nodes From Other Players"},
    'ChkFaceNodes': {'en': 'Face Nodes Before Gathering'},
    'ChkGatherHerbs': {'en': 'Gather Herbs'},
    'ChkGatherMinerals': {'en': 'Gather Minerals'},
    'ChkGatherChests': {'en': 'Gather Chests (Treasure)'},
    'ChkHarvestHerbs': {'en': 'Harvest Herbs'},
    'ChkHarvestMinerals': {'en': 'Harvest Mines'},
    'ChkRandomizeHotspots': {'en': 'Randomize Hotspot Order'},
    'ChkIgnoreElites': {'en': 'Ignore Elite Mobs'},
    'ChkShowAllDungeons': {'en': 'Show All Dungeons'},
    'LblMountName': {'en': 'Mount Name:'},
    'LblFlyingMount': {'en': 'Flying Mount:'},
    'LblMountDistance': {'en': 'Mount Distance:'},
    'LblDrinkAmount': {'en': 'Drink Amount:'},
    'LblFoodAmount': {'en': 'Food Amount:'},
    'LblMailRecipient': {'en': 'Mail Recipient:'},
    'LblFoodName': {'en': 'Food Name or ID:'},
    'LblDrinkName': {'en': 'Drink Name or ID:'},
    'LblBlacklistTimer': {'en': 'Blacklist Timer:'},
    'LblBottingHours': {'en': 'Botting Hours:'},
    'LblDetectionRange': {'en': 'Detection Range:'},
    'LblHeightModifier': {'en': 'Height Modifier:'},
    'LblLogLevel': {'en': 'Log Level:'},
    'LblLootRadius': {'en': 'Loot Radius:'},
    'LblMinFreeSlots': {'en': 'Min Free Slots:'},
    'LblMountUpDistance': {'en': 'Mount Up Distance:'},
    'LblPathType': {'en': 'Path Type:'},
    'LblPullDistance': {'en': 'Pull Distance:'},
    'LblQueue1': {'en': 'Queue #1:'},
    'LblQueue2': {'en': 'Queue #2:'},
    'LblRecipient': {'en': 'Recipient:'},
    'LblRepairBelow': {'en': 'Repair Below:'},
    'LblTicksPerSecond': {'en': 'Ticks Per Second:'},
    'LblMailQualities': {'en': 'Mail items of these qualities:'},
    'LblSellQualities': {'en': 'Sell items of these qualities at vendor:'},
    'LblBottingHoursLimit': {'en': 'Botting Hours (0 = no limit)'},
    'LblMailMax': {'en': 'Content (0 = no limit)'},
    'LblContent': {'en': 'Content'},
    'LogNone': {'en': 'None'},
    'LogQuiet': {'en': 'Quiet'},
    'LogNormal': {'en': 'Normal'},
    'LogDiagnostic': {'en': 'Diagnostic'},
    'LogVerbose': {'en': 'Verbose'},
    'PathBounce': {'en': 'Bounce'},
    'PathCircle': {'en': 'Circle'},
    'ColorBlue': {'en': 'Blue'},
    'ColorGreen': {'en': 'Green'},
    'ColorGrey': {'en': 'Grey'},
    'ColorPurple': {'en': 'Purple'},
    'ColorWhite': {'en': 'White'},
}

# Build base English (en-US)
for k, v in T.items():
    T[k]['en'] = T[k]['en']  # already en

# Now generate all language files.
# For simplicity, fall back to English when a translation is missing.
# We populate each language systematically. Each lang has all 160 strings.
# This is a quick auto-translation that needs human review.

TRANSLATIONS = {
    'fr-FR': {
        'AppTitle': 'CopilotBuddy', 'SettingsTitle': 'Paramètres & Outils', 'PluginsTitle': 'Plugins',
        'DeveloperToolsTitle': 'Outils développeur', 'SelectWoWTitle': 'Sélectionner un WoW',
        'SelectWoWDescription': 'Sélectionnez le processus WoW auquel vous attacher :',
        'LblAuthor': 'Auteur :', 'LblVersion': 'Version :', 'RecompileAll': 'Tout recompiler',
        'LblFactionName': 'Nom de faction :', 'LblGroupID': 'ID de groupe :',
        'LblGroupID2': 'ID de groupe 2 :', 'LblVendorType': 'Type de vendeur :',
        'LblRefresh': 'Actualiser', 'LblLoadProfileButtonText': 'Charger le profil',
        'LblPauseButtonText': 'Pause', 'LblEnhancedMode': 'Mode amélioré',
        'LblFromFileSystem': 'Depuis le système de fichiers', 'LblFromBuddyStore': 'Depuis le Buddy Store',
        'LblFromWebSource': 'Depuis le Web', 'LblRecent': 'Récents',
        'LblShowPath': 'Afficher le chemin', 'LblTargetInfo': 'Infos cible',
        'LblNavigation': 'Navigation',
        'ReportBug': 'Signaler un bug',
        'LblDungeonQueueType': "Vous devez changer le type de file en Spécifique avant d'éditer la liste des donjons",
        'TabBagItems': 'Objets du sac',
        'LogNoneDesc': 'Aucun : aucun log', 'LogQuietDesc': 'Silencieux : logs minimaux',
        'LogNormalDesc': 'Normal : logs standards', 'LogVerboseDesc': 'Verbeux : logs détaillés',
        'LogDiagnosticDesc': 'Diagnostic : tous les logs',
        'GroupLanguage': 'Langue',
        'LblLanguage': 'Langue :',
        'LangAuto': 'Auto (langue du système)',
        'LblLanguageRestart': "Redémarrez Honorbuddy pour appliquer les changements.",
        'BGBuddyConfigTitle': 'Config BGBuddy', 'DungeonBuddyConfigTitle': 'Config DungeonBuddy',
        'GatherBuddySettingsTitle': 'Paramètres GatherBuddy', 'TabLog': 'Journal', 'TabInfo': 'Infos',
        'TabProfiles': 'Profils', 'TabQuests': 'Quêtes', 'TabObjects': 'Objets', 'TabUnits': 'Unités',
        'Pause': 'Pause', 'Ready': 'Prêt', 'EnhancedMode': 'Mode amélioré', 'LoadProfile': 'Charger le profil',
        'Settings': 'Paramètres', 'BotConfig': 'Config bot', 'ClassConfig': 'Config classe',
        'Plugins': 'Plugins', 'DeveloperTools': 'Outils développeur', 'Start': 'Démarrer', 'Stop': 'Arrêter',
        'Navigation': 'Navigation', 'ShowPath': 'Afficher le chemin', 'TargetInfo': 'Infos cible',
        'ReloadScripts': 'Recharger scripts', 'DisableMovement': 'Désactiver déplacement',
        'EnableMovement': 'Activer déplacement', 'CopyXML': 'Copier XML', 'Refresh': 'Actualiser',
        'SaveAndClose': 'Enregistrer & Fermer', 'Cancel': 'Annuler', 'Select': 'Sélectionner',
        'SelectAll': 'Tout sélectionner', 'UnselectAll': 'Tout désélectionner',
        'GenerateBlackspot': 'Générer zone interdite', 'GenerateHotspot': 'Générer point chaud',
        'GroupGeneral': 'Général', 'GroupLogging': 'Journalisation', 'GroupMount': 'Monture',
        'GroupVendorsFlightPaths': 'Vendeurs & Routes de vol', 'GroupMailRefreshments': 'Courrier et Rafraîchissements',
        'GroupCombatLoot': 'Combat / Butin', 'GroupDeathSafety': 'Mort / Sécurité',
        'GroupGathering': 'Cueillette', 'GroupAntiNinja': 'Anti-Voleur', 'GroupHerbs': 'Herbes',
        'GroupMinerals': 'Minerais', 'GroupBagItems': 'Objets du sac', 'GroupBossList': 'Liste des boss',
        'GroupCommon': 'Commun', 'GroupCopyInfo': 'Copier les infos', 'GroupCopyXML': 'Copier XML',
        'GroupCurrentTargetInfo': 'Infos cible actuelle', 'GroupDistance': 'Distance',
        'GroupDungeonList': 'Liste des donjons', 'GroupDungeonSelection': 'Sélection du donjon',
        'GroupEntry': 'Entrée', 'GroupFactionID': 'ID de faction', 'GroupGUID': 'GUID',
        'GroupGameObjects': 'Objets du jeu', 'GroupLocalPlayerInfo': 'Infos joueur local',
        'GroupLockType': 'Type de verrou', 'GroupLootList': 'Liste du butin', 'GroupLooting': 'Butin',
        'GroupMail': 'Courrier', 'GroupName': 'Nom', 'GroupNavigation': 'Navigation',
        'GroupNodeSelection': 'Sélection du nœud', 'GroupPosition': 'Position',
        'GroupQueue': "File d'attente", 'GroupSecret': 'Secret',
        'GroupSellQualityFilters': 'Filtres de qualité de vente', 'GroupSessionTimer': 'Minuteur de session',
        'GroupSettings': 'Paramètres', 'GroupSpellFocus': 'Focalisation de sort',
        'GroupStackCount': 'Quantité', 'GroupTargetList': 'Liste des cibles', 'GroupType': 'Type',
        'GroupVendorRepair': 'Vendeur / Réparation', 'GroupViewAuras': 'Voir les auras',
        'ChkUseMount': 'Utiliser une monture', 'ChkRandomMount': 'Monture aléatoire',
        'ChkAutomatic': 'Automatique', 'ChkLearnFlightPaths': 'Apprendre les routes de vol',
        'ChkUseFlightPaths': 'Utiliser les routes de vol',
        'ChkFindVendorsAuto': 'Trouver les vendeurs automatiquement',
        'ChkTrainNewSkills': 'Former aux nouveaux sorts', 'ChkLogoutForInactivity': 'Déconnexion pour inactivité',
        'ChkUseFrameLock': 'Utiliser le verrou de cadre',
        'ChkKillBetweenHotspots': 'Tuer entre les points chauds',
        'ChkHearthExitTimer': 'Pierre de foyer & Quitter au minuteur',
        'ChkWaitRezSickness': 'Attendre la fin de la malédiction de résurrection',
        'ChkUseSpiritHealer': "Utiliser le guérisseur d'esprits (éviter la course au corps)",
        'ChkVendorWhenFull': 'Aller au vendeur quand les sacs sont pleins',
        'ChkRepairAtVendor': 'Réparer chez le vendeur', 'ChkSkinMobs': 'Dépecer les mobs',
        'ChkNinjaSkin': 'Vol de peau', 'ChkLootMobs': 'Butiner les mobs',
        'ChkLootChests': 'Butiner les coffres', 'ChkLootCorpses': 'Butiner les cadavres',
        'ChkMailToAlt': "Envoyer les objets à l'alt",
        'ChkNoNinja': 'Ne pas voler les nœuds des autres joueurs',
        'ChkFaceNodes': 'Faire face aux nœuds avant la cueillette',
        'ChkGatherHerbs': 'Cueillir les herbes', 'ChkGatherMinerals': 'Cueillir les minerais',
        'ChkGatherChests': 'Cueillir les coffres (trésor)',
        'ChkHarvestHerbs': 'Récolter les herbes', 'ChkHarvestMinerals': 'Récolter les mines',
        'ChkRandomizeHotspots': 'Ordre aléatoire des points chauds',
        'ChkIgnoreElites': 'Ignorer les mobs élites', 'ChkShowAllDungeons': 'Afficher tous les donjons',
        'LblMountName': 'Nom de la monture :', 'LblFlyingMount': 'Monture volante :',
        'LblMountDistance': 'Distance de monture :', 'LblDrinkAmount': 'Quantité de boisson :',
        'LblFoodAmount': 'Quantité de nourriture :', 'LblMailRecipient': 'Destinataire du courrier :',
        'LblFoodName': 'Nom de la nourriture ou ID :', 'LblDrinkName': 'Nom de la boisson ou ID :',
        'LblBlacklistTimer': 'Minuteur de liste noire :', 'LblBottingHours': 'Heures de bot :',
        'LblDetectionRange': 'Portée de détection :', 'LblHeightModifier': 'Modificateur de hauteur :',
        'LblLogLevel': 'Niveau de log :', 'LblLootRadius': 'Rayon de butin :',
        'LblMinFreeSlots': 'Emplacements libres min. :', 'LblMountUpDistance': 'Distance de montage :',
        'LblPathType': 'Type de chemin :', 'LblPullDistance': "Distance d'attraction :",
        'LblQueue1': 'File #1 :', 'LblQueue2': 'File #2 :', 'LblRecipient': 'Destinataire :',
        'LblRepairBelow': 'Réparer en dessous de :', 'LblTicksPerSecond': 'Ticks par seconde :',
        'LblMailQualities': 'Envoyer les objets de ces qualités :',
        'LblSellQualities': 'Vendre les objets de ces qualités au vendeur :',
        'LblBottingHoursLimit': 'Heures de bot (0 = aucune limite)',
        'LblMailMax': 'Contenu (0 = aucune limite)', 'LblContent': 'Contenu',
        'LogNone': 'Aucun', 'LogQuiet': 'Silencieux', 'LogNormal': 'Normal',
        'LogDiagnostic': 'Diagnostic', 'LogVerbose': 'Verbeux',
        'PathBounce': 'Rebondir', 'PathCircle': 'Cercle',
        'ColorBlue': 'Bleu', 'ColorGreen': 'Vert', 'ColorGrey': 'Gris',
        'ColorPurple': 'Violet', 'ColorWhite': 'Blanc',
    },
    'zh-Hans': {
        'AppTitle': '飞行员助手', 'SettingsTitle': '设置与工具', 'PluginsTitle': '插件',
        'DeveloperToolsTitle': '开发者工具', 'SelectWoWTitle': '选择 WoW',
        'SelectWoWDescription': '选择要附加的 WoW 进程：',
        'LblAuthor': '作者：', 'LblVersion': '版本：', 'RecompileAll': '全部重新编译',
        'LblFactionName': '阵营名称：', 'LblGroupID': '团队 ID：',
        'LblGroupID2': '团队 ID 2：', 'LblVendorType': '商人类型：',
        'LblRefresh': '刷新', 'LblLoadProfileButtonText': '加载配置',
        'LblPauseButtonText': '暂停', 'LblEnhancedMode': '增强模式',
        'LblFromFileSystem': '从文件系统', 'LblFromBuddyStore': '从 Buddy 商店',
        'LblFromWebSource': '从网络', 'LblRecent': '最近',
        'LblShowPath': '显示路径', 'LblTargetInfo': '目标信息',
        'LblNavigation': '导航',
        'ReportBug': '报告错误',
        'LblDungeonQueueType': '在编辑副本列表前，您需要将队列类型更改为指定',
        'TabBagItems': '背包物品',
        'LogNoneDesc': '无：无日志', 'LogQuietDesc': '安静：最少日志',
        'LogNormalDesc': '正常：标准日志', 'LogVerboseDesc': '详细：详细日志',
        'LogDiagnosticDesc': '诊断：所有日志',
        'GroupLanguage': '语言',
        'LblLanguage': '语言：',
        'LangAuto': '自动（系统默认）',
        'LblLanguageRestart': '重启 Honorbuddy 以使更改生效。',
        'BGBuddyConfigTitle': '战场机器人设置', 'DungeonBuddyConfigTitle': '副本机器人设置',
        'GatherBuddySettingsTitle': '采集机器人设置', 'TabLog': '日志', 'TabInfo': '信息',
        'TabProfiles': '配置文件', 'TabQuests': '任务', 'TabObjects': '物体', 'TabUnits': '单位',
        'Pause': '暂停', 'Ready': '就绪', 'EnhancedMode': '增强模式', 'LoadProfile': '加载配置',
        'Settings': '设置', 'BotConfig': '机器人设置', 'ClassConfig': '职业设置',
        'Plugins': '插件', 'DeveloperTools': '开发者工具', 'Start': '启动', 'Stop': '停止',
        'Navigation': '导航', 'ShowPath': '显示路径', 'TargetInfo': '目标信息',
        'ReloadScripts': '重新加载脚本', 'DisableMovement': '禁用移动',
        'EnableMovement': '启用移动', 'CopyXML': '复制 XML', 'Refresh': '刷新',
        'SaveAndClose': '保存并关闭', 'Cancel': '取消', 'Select': '选择',
        'SelectAll': '全选', 'UnselectAll': '全不选',
        'GenerateBlackspot': '生成黑名单', 'GenerateHotspot': '生成热点',
        'GroupGeneral': '常规', 'GroupLogging': '日志', 'GroupMount': '坐骑',
        'GroupVendorsFlightPaths': '商人与飞行路线', 'GroupMailRefreshments': '邮件与补给',
        'GroupCombatLoot': '战斗 / 拾取', 'GroupDeathSafety': '死亡 / 安全',
        'GroupGathering': '采集', 'GroupAntiNinja': '防抢怪', 'GroupHerbs': '草药',
        'GroupMinerals': '矿物', 'GroupBagItems': '背包物品', 'GroupBossList': '首领列表',
        'GroupCommon': '通用', 'GroupCopyInfo': '复制信息', 'GroupCopyXML': '复制 XML',
        'GroupCurrentTargetInfo': '当前目标信息', 'GroupDistance': '距离',
        'GroupDungeonList': '副本列表', 'GroupDungeonSelection': '副本选择',
        'GroupEntry': '入口', 'GroupFactionID': '阵营 ID', 'GroupGUID': 'GUID',
        'GroupGameObjects': '游戏物体', 'GroupLocalPlayerInfo': '本地玩家信息',
        'GroupLockType': '锁定类型', 'GroupLootList': '拾取列表', 'GroupLooting': '拾取',
        'GroupMail': '邮件', 'GroupName': '名称', 'GroupNavigation': '导航',
        'GroupNodeSelection': '节点选择', 'GroupPosition': '位置',
        'GroupQueue': '队列', 'GroupSecret': '密码',
        'GroupSellQualityFilters': '出售品质过滤', 'GroupSessionTimer': '会话计时器',
        'GroupSettings': '设置', 'GroupSpellFocus': '法术焦点',
        'GroupStackCount': '堆叠数量', 'GroupTargetList': '目标列表', 'GroupType': '类型',
        'GroupVendorRepair': '商人 / 修理', 'GroupViewAuras': '查看光环',
        'ChkUseMount': '使用坐骑', 'ChkRandomMount': '随机坐骑',
        'ChkAutomatic': '自动', 'ChkLearnFlightPaths': '学习飞行路线',
        'ChkUseFlightPaths': '使用飞行路线',
        'ChkFindVendorsAuto': '自动寻找商人',
        'ChkTrainNewSkills': '训练新技能', 'ChkLogoutForInactivity': '闲置自动登出',
        'ChkUseFrameLock': '使用帧锁定',
        'ChkKillBetweenHotspots': '在热点击杀',
        'ChkHearthExitTimer': '炉石 & 定时退出',
        'ChkWaitRezSickness': '等待复活虚弱结束',
        'ChkUseSpiritHealer': '使用灵魂医者（跳过跑尸体）',
        'ChkVendorWhenFull': '背包满时去商人',
        'ChkRepairAtVendor': '在商人处修理', 'ChkSkinMobs': '剥皮怪物',
        'ChkNinjaSkin': '抢皮', 'ChkLootMobs': '拾取怪物',
        'ChkLootChests': '拾取宝箱', 'ChkLootCorpses': '拾取尸体',
        'ChkMailToAlt': '邮寄物品给小号',
        'ChkNoNinja': '不要抢其他玩家的节点',
        'ChkFaceNodes': '采集前面向节点',
        'ChkGatherHerbs': '采集草药', 'ChkGatherMinerals': '采集矿石',
        'ChkGatherChests': '采集宝箱（宝藏）',
        'ChkHarvestHerbs': '收割草药', 'ChkHarvestMinerals': '开采矿脉',
        'ChkRandomizeHotspots': '随机化热点顺序',
        'ChkIgnoreElites': '忽略精英怪', 'ChkShowAllDungeons': '显示所有副本',
        'LblMountName': '坐骑名称：', 'LblFlyingMount': '飞行坐骑：',
        'LblMountDistance': '坐骑距离：', 'LblDrinkAmount': '饮水数量：',
        'LblFoodAmount': '食物数量：', 'LblMailRecipient': '邮件收件人：',
        'LblFoodName': '食物名称或 ID：', 'LblDrinkName': '饮水名称或 ID：',
        'LblBlacklistTimer': '黑名单计时：', 'LblBottingHours': '挂机时间：',
        'LblDetectionRange': '探测范围：', 'LblHeightModifier': '高度修正：',
        'LblLogLevel': '日志级别：', 'LblLootRadius': '拾取半径：',
        'LblMinFreeSlots': '最少空位：', 'LblMountUpDistance': '上坐骑距离：',
        'LblPathType': '路径类型：', 'LblPullDistance': '拉怪距离：',
        'LblQueue1': '队列 #1：', 'LblQueue2': '队列 #2：', 'LblRecipient': '收件人：',
        'LblRepairBelow': '修理阈值：', 'LblTicksPerSecond': '每秒 tick 数：',
        'LblMailQualities': '邮寄以下品质的物品：',
        'LblSellQualities': '出售以下品质的物品：',
        'LblBottingHoursLimit': '挂机时间（0 = 无限制）',
        'LblMailMax': '容量（0 = 无限制）', 'LblContent': '内容',
        'LogNone': '无', 'LogQuiet': '安静', 'LogNormal': '正常',
        'LogDiagnostic': '诊断', 'LogVerbose': '详细',
        'PathBounce': '弹跳', 'PathCircle': '圆形',
        'ColorBlue': '蓝色', 'ColorGreen': '绿色', 'ColorGrey': '灰色',
        'ColorPurple': '紫色', 'ColorWhite': '白色',
    },
    'zh-Hant': {},  # Falls back to English (or zh-Hans)
    'ru-RU': {
        'AppTitle': 'CopilotBuddy', 'SettingsTitle': 'Настройки и инструменты', 'PluginsTitle': 'Плагины',
        'DeveloperToolsTitle': 'Инструменты разработчика', 'SelectWoWTitle': 'Выбрать WoW',
        'SelectWoWDescription': 'Выберите процесс WoW для подключения:',
        'LblAuthor': 'Автор:', 'LblVersion': 'Версия:', 'RecompileAll': 'Перекомпилировать всё',
        'LblFactionName': 'Имя фракции:', 'LblGroupID': 'ID группы:',
        'LblGroupID2': 'ID группы 2:', 'LblVendorType': 'Тип вендора:',
        'LblRefresh': 'Обновить', 'LblLoadProfileButtonText': 'Загрузить профиль',
        'LblPauseButtonText': 'Пауза', 'LblEnhancedMode': 'Расширенный режим',
        'LblFromFileSystem': 'Из файловой системы', 'LblFromBuddyStore': 'Из Buddy Store',
        'LblFromWebSource': 'Из веб', 'LblRecent': 'Недавние',
        'LblShowPath': 'Показать путь', 'LblTargetInfo': 'Инфо цели',
        'LblNavigation': 'Навигация',
        'ReportBug': 'Сообщить об ошибке',
        'LblDungeonQueueType': 'Сначала измените тип очереди на "Определённая" перед редактированием списка подземелий',
        'TabBagItems': 'Предметы в сумке',
        'LogNoneDesc': 'Нет: без логов', 'LogQuietDesc': 'Тихо: минимум логов',
        'LogNormalDesc': 'Нормально: стандартные логи', 'LogVerboseDesc': 'Подробно: детальные логи',
        'LogDiagnosticDesc': 'Диагностика: все логи',
        'GroupLanguage': 'Язык',
        'LblLanguage': 'Язык:',
        'LangAuto': 'Авто (язык системы)',
        'LblLanguageRestart': 'Перезапустите Honorbuddy для применения изменений.',
        'BGBuddyConfigTitle': 'Настройки BGBuddy', 'DungeonBuddyConfigTitle': 'Настройки DungeonBuddy',
        'GatherBuddySettingsTitle': 'Настройки GatherBuddy', 'TabLog': 'Журнал', 'TabInfo': 'Инфо',
        'TabProfiles': 'Профили', 'TabQuests': 'Задания', 'TabObjects': 'Объекты', 'TabUnits': 'Существа',
        'Pause': 'Пауза', 'Ready': 'Готов', 'EnhancedMode': 'Расширенный режим',
        'LoadProfile': 'Загрузить профиль', 'Settings': 'Настройки', 'BotConfig': 'Конфиг бота',
        'ClassConfig': 'Конфиг класса', 'Plugins': 'Плагины', 'DeveloperTools': 'Инструменты',
        'Start': 'Запуск', 'Stop': 'Стоп', 'Navigation': 'Навигация', 'ShowPath': 'Показать путь',
        'TargetInfo': 'Инфо цели', 'ReloadScripts': 'Перезагрузить скрипты',
        'DisableMovement': 'Отключить движение', 'EnableMovement': 'Включить движение',
        'CopyXML': 'Копировать XML', 'Refresh': 'Обновить', 'SaveAndClose': 'Сохранить и закрыть',
        'Cancel': 'Отмена', 'Select': 'Выбрать', 'SelectAll': 'Выбрать все',
        'UnselectAll': 'Снять выбор', 'GenerateBlackspot': 'Создать чёрный список',
        'GenerateHotspot': 'Создать горячую точку', 'GroupGeneral': 'Основные',
        'GroupLogging': 'Логирование', 'GroupMount': 'Маунт',
        'GroupVendorsFlightPaths': 'Вендоры и маршруты',
        'GroupMailRefreshments': 'Почта и Закуски', 'GroupCombatLoot': 'Бой / Лут',
        'GroupDeathSafety': 'Смерть / Безопасность', 'GroupGathering': 'Сбор',
        'GroupAntiNinja': 'Анти-нуб', 'GroupHerbs': 'Травы', 'GroupMinerals': 'Руды',
        'GroupBagItems': 'Предметы в сумке', 'GroupBossList': 'Список боссов',
        'GroupCommon': 'Общее', 'GroupCopyInfo': 'Копировать инфо', 'GroupCopyXML': 'Копировать XML',
        'GroupCurrentTargetInfo': 'Инфо текущей цели', 'GroupDistance': 'Расстояние',
        'GroupDungeonList': 'Список подземелий', 'GroupDungeonSelection': 'Выбор подземелья',
        'GroupEntry': 'Вход', 'GroupFactionID': 'ID фракции', 'GroupGUID': 'GUID',
        'GroupGameObjects': 'Игровые объекты', 'GroupLocalPlayerInfo': 'Инфо игрока',
        'GroupLockType': 'Тип замка', 'GroupLootList': 'Список лута', 'GroupLooting': 'Лут',
        'GroupMail': 'Почта', 'GroupName': 'Имя', 'GroupNavigation': 'Навигация',
        'GroupNodeSelection': 'Выбор узла', 'GroupPosition': 'Позиция',
        'GroupQueue': 'Очередь', 'GroupSecret': 'Секрет',
        'GroupSellQualityFilters': 'Фильтры качества продажи',
        'GroupSessionTimer': 'Таймер сессии', 'GroupSettings': 'Настройки',
        'GroupSpellFocus': 'Фокус заклинания', 'GroupStackCount': 'Количество',
        'GroupTargetList': 'Список целей', 'GroupType': 'Тип',
        'GroupVendorRepair': 'Вендор / Ремонт', 'GroupViewAuras': 'Просмотр аур',
        'ChkUseMount': 'Использовать маунт', 'ChkRandomMount': 'Случайный маунт',
        'ChkAutomatic': 'Автоматически', 'ChkLearnFlightPaths': 'Изучать маршруты',
        'ChkUseFlightPaths': 'Использовать маршруты',
        'ChkFindVendorsAuto': 'Найти вендоров автоматически',
        'ChkTrainNewSkills': 'Изучать новые навыки',
        'ChkLogoutForInactivity': 'Выйти при бездействии',
        'ChkUseFrameLock': 'Использовать блокировку кадра',
        'ChkKillBetweenHotspots': 'Убивать между точками',
        'ChkHearthExitTimer': 'Камень дома и выход по таймеру',
        'ChkWaitRezSickness': 'Ждать окончание болезни',
        'ChkUseSpiritHealer': 'Использовать целителя душ',
        'ChkVendorWhenFull': 'К вендору при полных сумках',
        'ChkRepairAtVendor': 'Ремонтировать у вендора', 'ChkSkinMobs': 'Снимать шкуры',
        'ChkNinjaSkin': 'Воровать шкуры', 'ChkLootMobs': 'Лутать мобов',
        'ChkLootChests': 'Лутать сундуки', 'ChkLootCorpses': 'Лутать трупы',
        'ChkMailToAlt': 'Отправить предметы альту',
        'ChkNoNinja': 'Не воровать узлы у других',
        'ChkFaceNodes': 'Смотреть на узел перед сбором',
        'ChkGatherHerbs': 'Собирать травы', 'ChkGatherMinerals': 'Собирать руду',
        'ChkGatherChests': 'Собирать сундуки (сокровища)',
        'ChkHarvestHerbs': 'Собирать травы', 'ChkHarvestMinerals': 'Добывать руду',
        'ChkRandomizeHotspots': 'Случайный порядок точек',
        'ChkIgnoreElites': 'Игнорировать элитных мобов',
        'ChkShowAllDungeons': 'Показать все подземелья',
        'LblMountName': 'Имя маунта:', 'LblFlyingMount': 'Летающий маунт:',
        'LblMountDistance': 'Дистанция маунта:', 'LblDrinkAmount': 'Кол-во напитка:',
        'LblFoodAmount': 'Кол-во еды:', 'LblMailRecipient': 'Получатель почты:',
        'LblFoodName': 'Имя еды или ID:', 'LblDrinkName': 'Имя напитка или ID:',
        'LblBlacklistTimer': 'Таймер ЧС:', 'LblBottingHours': 'Часы бота:',
        'LblDetectionRange': 'Дальность обнаружения:', 'LblHeightModifier': 'Модификатор высоты:',
        'LblLogLevel': 'Уровень лога:', 'LblLootRadius': 'Радиус лута:',
        'LblMinFreeSlots': 'Мин. свободных слотов:', 'LblMountUpDistance': 'Дистанция для маунта:',
        'LblPathType': 'Тип пути:', 'LblPullDistance': 'Дистанция подтягивания:',
        'LblQueue1': 'Очередь #1:', 'LblQueue2': 'Очередь #2:', 'LblRecipient': 'Получатель:',
        'LblRepairBelow': 'Ремонтировать ниже:', 'LblTicksPerSecond': 'Тиков в секунду:',
        'LblMailQualities': 'Отправлять предметы этого качества:',
        'LblSellQualities': 'Продавать предметы этого качества:',
        'LblBottingHoursLimit': 'Часы бота (0 = без лимита)',
        'LblMailMax': 'Содержимое (0 = без лимита)', 'LblContent': 'Содержимое',
        'LogNone': 'Нет', 'LogQuiet': 'Тихо', 'LogNormal': 'Нормально',
        'LogDiagnostic': 'Диагностика', 'LogVerbose': 'Подробно',
        'PathBounce': 'Отскок', 'PathCircle': 'Круг',
        'ColorBlue': 'Синий', 'ColorGreen': 'Зелёный', 'ColorGrey': 'Серый',
        'ColorPurple': 'Фиолетовый', 'ColorWhite': 'Белый',
    },
    'de-DE': {},  # Falls back to English
    'es-ES': {},  # Falls back to English
    'it-IT': {},  # Falls back to English
    'ko-KR': {},  # Falls back to English
    'tr-TR': {},  # Falls back to English
    'pt-PT': {},  # Falls back to English
    'pl-PL': {},  # Falls back to English
    'ja-JP': {},  # Falls back to English
    'nl-NL': {},  # Falls back to English
    'cs-CZ': {},  # Falls back to English
}

base = sys.argv[1]
for lang in LANGS:
    translations = []
    for key, en_val in T.items():
        if lang == 'en':
            val = en_val['en']
        else:
            # Try target lang, then fall back to en
            val = TRANSLATIONS.get(lang, {}).get(key, en_val['en'])
        translations.append((key, val))
    suffix = '' if lang == 'en' else '.' + lang
    gen(base + suffix + '.resx', translations)

print(f'Generated {len(T)} translations x {len(LANGS)} languages at {base}')